import Layout from '@/components/Layout'
import '@/styles/globals.css'
import Head from 'next/head'

import { store } from '@/redux/store/Store'
import { Provider } from 'react-redux'

export default function App({ Component, pageProps }) {

  return (
    
      <Provider store={store}>
        <Head>
          <title>Ecom</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>


        <Layout ><Component {...pageProps} /></Layout>

      </Provider>

    
  )
}

